// <auto-generated />
using System;
using FashionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FashionApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FashionApi.DTO.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int?>("DanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSanPham");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("FashionApi.DTO.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoaiDanhMuc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaDanhMuc");

                    b.HasIndex("TenDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("FashionApi.DTO.GiaoDien", b =>
                {
                    b.Property<int>("MaGiaoDien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDien"));

                    b.Property<int>("LoaiGiaoDien")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("TenGiaoDien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaGiaoDien");

                    b.HasIndex("LoaiGiaoDien");

                    b.HasIndex("TenGiaoDien");

                    b.ToTable("GiaoDiens");
                });

            modelBuilder.Entity("FashionApi.DTO.Media", b =>
                {
                    b.Property<int>("MaMedia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMedia"));

                    b.Property<string>("AltMedia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkMedia")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiMedia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaBinhLuan")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiaoDien")
                        .HasColumnType("int");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaMedia");

                    b.HasIndex("MaBinhLuan");

                    b.HasIndex("MaGiaoDien")
                        .IsUnique()
                        .HasFilter("[MaGiaoDien] IS NOT NULL");

                    b.HasIndex("MaSanPham");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("FashionApi.DTO.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Avt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GioiTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TieuSu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("TimeKhoa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("FashionApi.DTO.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<decimal>("GiaBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("GiaSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GioiTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("MaHashtag")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<int>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MaVach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaHashtag");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaThuongHieu");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TenSanPham");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("FashionApi.DTO.BinhLuan", b =>
                {
                    b.HasOne("FashionApi.DTO.NguoiDung", "NguoiDungNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BinhLuan_NguoiDung");

                    b.HasOne("FashionApi.DTO.SanPham", "SanPhamNavigation")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_BinhLuan_SanPham");

                    b.Navigation("NguoiDungNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("FashionApi.DTO.Media", b =>
                {
                    b.HasOne("FashionApi.DTO.BinhLuan", "BinhLuanNavigation")
                        .WithMany("Medias")
                        .HasForeignKey("MaBinhLuan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Media_BinhLuan");

                    b.HasOne("FashionApi.DTO.GiaoDien", "GiaoDienNavigation")
                        .WithOne("Media")
                        .HasForeignKey("FashionApi.DTO.Media", "MaGiaoDien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Media_GiaoDien");

                    b.HasOne("FashionApi.DTO.SanPham", "SanPhamNavigation")
                        .WithMany("Medias")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Media_SanPham");

                    b.Navigation("BinhLuanNavigation");

                    b.Navigation("GiaoDienNavigation");

                    b.Navigation("SanPhamNavigation");
                });

            modelBuilder.Entity("FashionApi.DTO.SanPham", b =>
                {
                    b.HasOne("FashionApi.DTO.DanhMuc", "DanhMucHashtag")
                        .WithMany()
                        .HasForeignKey("MaHashtag")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SanPham_DanhMuc_Hashtag");

                    b.HasOne("FashionApi.DTO.DanhMuc", "DanhMucLoai")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_DanhMuc_Loai");

                    b.HasOne("FashionApi.DTO.DanhMuc", "DanhMucThuongHieu")
                        .WithMany()
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_DanhMuc_ThuongHieu");

                    b.Navigation("DanhMucHashtag");

                    b.Navigation("DanhMucLoai");

                    b.Navigation("DanhMucThuongHieu");
                });

            modelBuilder.Entity("FashionApi.DTO.BinhLuan", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("FashionApi.DTO.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FashionApi.DTO.GiaoDien", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("FashionApi.DTO.NguoiDung", b =>
                {
                    b.Navigation("BinhLuans");
                });

            modelBuilder.Entity("FashionApi.DTO.SanPham", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
